### ISSUE TITLE
Snackbar does not show if keyboard is visible

### ISSUE THREAD

**Issue by i906** [nispok/snackbar#10]
Most likely the snackbar appeared under the keyboard

**Comment by myanimal** [comment]
@wmora with windowSoftInputMode set to adjustResize, it works as expect on Android 4.1, but not on my Nexus 5 running 5.1. Haven't tested on any other versions.

The window does resize correctly, but the snackbar remains below the keyboard.

I've tried removing all theme properties specific to v21 with no effect. Not sure if this is something specific to me though. Can anyone reproduce this?

**Comment by jdzuri** [comment]
+1 I have the same issue in Nexus 5 running 5.1

Have some mode to detect if keyboard is visible? Then, I can show the snackbar on the top.
