### ISSUE TITLE
Dismiss by replace should change the current snackbar's content instead of dismissing it

### ISSUE THREAD

**Issue by hatemsh** [nispok/snackbar#107]
This is not mentioned in the guidelines but is present in some of google's own apps like Google Keep and Chrome. If a snackbar needs to show while the previous one is still showing, the content of the previous snackbar is replaced and the duration of the snackbar is reset. This is much smoother than the dismiss and show behaviour.

**Comment by RubyDerBoss** [comment]
+1

**Comment by hatemsh** [comment]
I fixed this and create a pull request #108

**Comment by wmora** [comment]
closed via #108
