### ISSUE TITLE
How to make the Snackbar showing on top 'below' the toolbar ?

### ISSUE THREAD

**Issue by Jakmotiondata** [nispok/snackbar#114]
Hi, I try to implement the snackbar at the top of an activity (which handle 3 fragments in a tabhost). Neverthless I want it to show just under the toolbar, but after searching for a long moment, I stil having my snackbar showing (and hiding the toolbar). Do you have any solution to this ? Thanks a lot !

**Comment by amalChandran** [comment]
where is the solution.. do post it here.

**Comment by ramden** [comment]
Same problem 
+1

**Comment by apurvpandey** [comment]
Snackbar.with(SnackbarSampleActivity.this)
					            .position(Snackbar.SnackbarPosition.TOP)
					            .margin(25, 15)
					            .text("Single-line TOP Inside LinearLayout")
