### ISSUE TITLE
Is there a way to have multiple Actions in the same snack?

### ISSUE THREAD

**Issue by somghosh** [nispok/snackbar#121]
I want to make a non-obtrusive survey saying 

Where did you hear about us?
Facebook	     Twitter     Google    From Friends

And put these two lines, the words in the second line being the different actions.

How can I achieve this with a snackbar?

**Comment by wmora** [comment]
This cannot be done. The Google design specs doesn't allow for multiple actions, you can only have one.

**Comment by somghosh** [comment]
Thanks @wmora , if I need to build this feature as a custom on your existing repo - where should I start putting these 2-3 more actions?

**Comment by wmora** [comment]
Start by editing sb_template. Add your action buttons there
