### ISSUE TITLE
Snackbar with Timer: is it possible?

### ISSUE THREAD

**Issue by diofeher** [nispok/snackbar#123]
Guys, with this project is it possible to create a timer like that?
![screen shot 2015-05-12 at 12 08 29 am](https://cloud.githubusercontent.com/assets/161360/7579487/005d52fe-f83b-11e4-94a4-f0151e9a2fd7.png)

**Comment by wmora** [comment]
@diofeher what would the timer do? You can set a custom duration to the Snackbar, if that's what you mean

**Comment by diofeher** [comment]
@wmora I wanted to put a sticky snackbar in the bottom with a timer. Would start in 0 seconds going to 30 or 90 seconds. I'm doing a workout app.
