### ISSUE TITLE
Set Right to left direction 

### ISSUE THREAD

**Issue by atahani** [nispok/snackbar#58]
it's great to use SnackBar in non Lollipop android version, and have lot of option for developer,
i want to use snakeBar with RightToLeft Direction like this :

![righttolefrsnakes](https://cloud.githubusercontent.com/assets/1076900/5562261/734cf67a-8e23-11e4-8c33-53b67ce85f17.png)

try this code to set RTL direction, but it's not work !?
```java
Snackbar snackbar=Snackbar.with(getApplicationContext())
      .duration(Snackbar.SnackbarDuration.LENGTH_INDEFINITE)
      .text("متاسفانه خطایی در ثبت مکان رخ داده است. ")
      .actionLabel("بستن");
snackbar.setLayoutDirection(SnackbarLayout.LAYOUT_DIRECTION_RTL);
snackbar.setTextAlignment(View.TEXT_ALIGNMENT_TEXT_START);
SnackbarManager.show(snackbar,GetActivity());
```
is there any solution to set Direction Like this ?

**Comment by wmora** [comment]
Are you suggesting another layout with the proper order for RTL and let the user specify it? What would happen if the user changes the phone language back to a LTR one? Would you specify again the orientation?

**Comment by atahani** [comment]
i think should first get current direction in runtime and then set different snackbar layout direction  , found this solution for support in all of the API level :
```java
public static boolean isRTL(Locale locale) {
        final int directionality = Character.getDirectionality(locale.getDisplayName().charAt(0));
        return directionality == Character.DIRECTIONALITY_RIGHT_TO_LEFT ||
                directionality == Character.DIRECTIONALITY_RIGHT_TO_LEFT_ARABIC;
    }
//and get current locale by 
Locale currentLocale = getResources().getConfiguration().locale; 
if(isRTL(currentLocale)){
  //set RTL layout
}
else {
 //set default layout
}
```
so if user change Language to LTR one ,it's work as expected.

**Comment by starbug1** [comment]
@atahani: salam jenab tahani? khobid? I want to use snackbar in my app and my texts are in RTL format. can i use this library for my purpose? Thanks.

**Comment by atahani** [comment]
This library is deprecated, now you can use from [android support design library](http://android-developers.blogspot.com/2015/05/android-design-support-library.html)
It's support RTL direction in API > 17 , And for lower API version should set custom layout.

**Comment by arefbhrn** [comment]
Just use ViewCompat.setLayoutDirection(view, direction) using android.support.v4.view
Ex: ViewCompat.setLayoutDirection(findViewById(R.id.my_view), ViewCompat.LAYOUT_DIRECTION_RTL);
