### ISSUE TITLE
MultiLine don't work on Nexus 7 with Android 5.0

### ISSUE THREAD

**Issue by RubenBS** [nispok/snackbar#59]
![screenshot_2015-01-04-02-30-36](https://cloud.githubusercontent.com/assets/10385434/5604380/d4b26404-93b9-11e4-9913-1666a5fcfc2c.png)

MultiLine don't work on Nexus 7 with Android 5.0, I tried using the library in my application and testing the sample application.

Regards

**Comment by wmora** [comment]
Duplicate of #56. That's the intended behavior. The specs only mention multi line snackbars for phones. Tablets are always single line

**Comment by wmora** [comment]
Added a note about this in the README file
