### ISSUE TITLE
show() as a child view

### ISSUE THREAD

**Issue by KennyGoers** [nispok/snackbar#62]
Would it be possible to allow "showing" to place the snackbar as a child of a parent view? This would fix the problem with having to adjust views to show outside of it (FloatingActionButton's, etc).

**Comment by wmora** [comment]
You mean a `show(View targetView)` method in addition to 'show(Activity targetActivity)'?

**Comment by KennyGoers** [comment]
Yes, that way it could be made a child view of the fragment for example, and not need extra handling when in a view pager...

**Comment by h6ah4i** [comment]
+1

**Comment by KennyGoers** [comment]
William, yes, I think it would be doable to add the snackbar to a view in
such a way that that it would add the snackbar to the view hierarchy
appropriate to the phone or tablet. I think it would make adjusting
overlapping views much easier on the phone side.

**Comment by wmora** [comment]
fixed in [2.9.0](https://github.com/nispok/snackbar/releases/tag/v2.9.0)
