### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by alexey-rabets** [nispok/snackbar#64]
I use a snackbar with the custom duration 10 sec. If a user presses Back when a snackbar is showing, then the activity is finished but it cannot be garbage collected because there is a strong reference to it from the handler queue (due to postDelayed() method call):

Handler -> mDismissRunnable -> Snackbar (outer class) -> Activity

I think it is needed to call removeCallbacks(mDismissRunnable); from onDetachedFromWindow(), for example.

**Comment by wmora** [comment]
Thanks for reporting this. As a workaround, could you dismiss all Snackbars on your `onPause()` method?

**Comment by alexey-rabets** [comment]
I don't think that dismissing a snackbar eliminates the memory leak. As I see from the source code removeCallbacks(mDismissRunnable) is only called when swiping a snackbar. So if I would call dismiss() in onPause() a reference to the activity is still exists and will be only destroyed when postDelayed() is fired.

**Comment by wmora** [comment]
I see. Will upload a version shortly with the call in `onDetachedFromWindow()` as you suggested. It's probably the best place to remove the callbacks

**Comment by wmora** [comment]
Released in 2.7.4
