### ISSUE TITLE
Make snackbar undoable

### ISSUE THREAD

**Issue by alosdev** [nispok/snackbar#73]
Hi *,
it wold be nice, if this library also handle undo logic, so we don't need to handle two different libraries. An example is the https://github.com/jenzz/Android-UndoBar/ library. Or create something custom/ proprietary.
Thanks
Hasan

**Comment by AOrobator** [comment]
Just set your button text to UNDO and handle the undo logic yourself. It'd be too complicated for the library to handle undo logic when there's so many use cases and scenarios for every app.

**Comment by alosdev** [comment]
It's not the point of handling the undo-logic. It is more a listener which tells me, if the the user clicked the actionbutton or it just disappeared/ dismissed.
see

   ```java
     /**
     * Listener for actions of the undo bar.
     */
     public interface Listener {
        /**
         * Will be fired when the undo bar disappears without being actioned.
         */
        void onHide();

        /**
         * Will be fired when the undo button is pressed.
         */
        void onUndo(Parcelable token);
    }
```

**Comment by wmora** [comment]
Why wouldn't you use the listeners already provided?

`ActionClickListener#onActionClicked` will let you know if the user tapped the action button. Use the methods provided in `EventListener` for everything else.

If anything there could be a `actionClicked` field letting you know that the action was indeed tapped and just get its value when `onDismissed` is fired

**Comment by alosdev** [comment]
currently I'm using something like that:

    public interface UndoListener {
      void onDismissed();
  
      void undo();
    }

    private static class CombinedListener implements ActionClickListener, EventListener {
      private SnackBarHelper.UndoListener listener;

      private CombinedListener(UndoListener listener) {
        this.listener = listener;
      }

      @Override
      public void onActionClicked(Snackbar snackbar) {
        if (null != listener) {
          listener.undo();
          listener = null;
        }
      }

      @Override
      public void onShow(Snackbar snackbar) {
      }

      @Override
      public void onShown(Snackbar snackbar) {
      }

      @Override
      public void onDismiss(Snackbar snackbar) {
      }

      @Override
      public void onDismissed(Snackbar snackbar) {
        if (null != listener) {
          listener.onDismissed();
          listener = null;
        }
      }
    }


It would be nice to have in the library :)
