### ISSUE TITLE
Action button text should be Roboto Medium

### ISSUE THREAD

**Issue by ashughes** [nispok/snackbar#8]
According to the Material Design spec, the action button text should be Roboto Medium, while the message text should be Roboto Regular. I was looking into how to do this, but there doesn't seem to be an easy solution.

One option would be to bundle the Roboto Medium (and Roboto Regular?) fonts with the library and set the TextViews accordingly.

Another option is to add a dependency for a library like
https://github.com/johnkil/Android-RobotoTextView
or
https://github.com/chrisjenx/Calligraphy

I also just came across https://bitbucket.org/josephearl/foundry, which might be helpful.

Any other ideas/thoughts?

**Comment by tsvetova** [comment]
What this really fixed? I checked out the sources, but Roboto isn't mentioned anywhere. Instead sans-serif-medium is specified as font-family in styles.xml. Or am I missing something?

**Comment by davidjrichardson** [comment]
sans-serif-medium the system font alias for Roboto medium for >= API 21 (Lollipop). To get the font on lower APIs (< API 21) you'd need to include the TTF with your APK and alter typefaces manually.

**Comment by tsvetova** [comment]
I see, thanks. What about roboto regular?

**Comment by davidjrichardson** [comment]
I believe the library will default to Roboto regular on < API 21 devices (when I issued the pull request to the lib it was bold but the style has since changed)

**Comment by tsvetova** [comment]
Ok, thanks again.
